name: clean_architecture_posts
description: Posts App with Clean Architecture

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.3.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Bloc For state management
  flutter_bloc: ^8.1.3
  # Functional Programming things
  dartz: ^0.10.1
  # value equality
  equatable: ^2.0.5
  # Service Locator
  get_it: ^7.6.4
  # Local Cache
  shared_preferences: ^2.2.2
  # Remote Api
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

